<?php

return array(
	'layout' => '//layouts/backend',
	'isDeleteDisabled' => false,
	'moduleCode' => 'f7',
	'isAllowMeta' => true,
	'foreignRefer' => array('key' => 'id', 'title' => 'title'),
	'menuTemplate' => array(
		'index' => 'admin, create',
		'admin' => 'create',
		'create' => 'admin',
		'update' => 'admin, create, view',
		'view' => 'admin, create, update, delete',
	),
	'admin' => array(
		'list' => array('id', 'title', 'date_started', 'is_active', 'is_highlight'),
		'sortDefaultOrder' => 't.date_started DESC',
	),
	'structure' => array(
		'code' => array(
			'isUnique' => true,
			'isUUID' => true,
		),
		'slug' => array(
			'isUnique' => true,
			'isUUID' => false,
		),
		'json_extra' => array('isJson' => true),
	),
	// this foreignKey is mainly for crud view generation. model relationship will not use this at the moment
	'json' => array(
		'extra' => array(
		),
	),
	'foreignKey' => array(
	),
	/*
		eg: resource (this table), industry(target table), resource2industry(linked table)
		key: target table name, all small case singular form, eg 'industry'
		className: the model name of target table, CamelCase with uppercase first character, eg 'Industry'
		relationName: the MANY_MANY relations key generated by yii, all small case plural form of target table name, eg 'industries'
		relationTable: the linked table name, eg 'resource2industry'
		linkClassName: optional, if not provided, CamelCase with uppercase first character of relationTable, eg Resource2Industry
		label: optional
		notMasterData: optional boolean, default: false. If set true, means the target table can be huge so the input method will be different
	*/
	'many2many' => array(
		'industry' => array('className' => 'Industry', 'relationName' => 'industries', 'relationTable' => 'industry2intake'),

		'persona' => array('className' => 'Persona', 'relationName' => 'personas', 'relationTable' => 'persona2intake'),

		'startup_stage' => array('className' => 'StartupStage', 'relationName' => 'startupStages', 'relationTable' => 'startup_stage2intake'),

		'impact' => array('className' => 'Impact', 'relationName' => 'impacts', 'relationTable' => 'impact2intake'),

		'sdg' => array('className' => 'Sdg', 'relationName' => 'sdgs', 'relationTable' => 'sdg2intake'),
	),

	'tag' => array(
		'backend' => array(
			'tagTable' => 'tag', 'tagBindingTable' => 'tag2intake', 'modelTableFk' => 'intake_id', 'tagTablePk' => 'id', 'tagTableName' => 'name', 'tagBindingTableTagId' => 'tag_id', 'cacheID' => 'cacheTag2Intake'),
	),
);
