<?php

return array(
	'layout' => 'layouts.backend',
	'isDeleteDisabled' => true,
	'moduleCode' => '',
	'isAllowMeta' => true,
	'foreignRefer' => array('key' => 'id', 'title' => 'title'),
	'menuTemplate' => array(
		'index' => 'admin, create',
		'admin' => 'create',
		'create' => 'admin',
		'update' => 'admin, create, view',
		'view' => 'admin, create, update, delete',
	),
	'admin' => array(
		'list' => array('id', 'vendor', 'vendor_code', 'title', 'date_started', 'at', 'is_active'),
		'sortDefaultOrder' => 't.date_started DESC',
	),
	'structure' => array(
		'code' => array(
			'isUnique' => true,
			'isUUID' => true,
		),
		'vendor_code' => array('isHiddenInForm' => true),
		'latlong_address' => array('isSpatial' => true),
		'json_extra' => array('isJson' => true),
		'json_original' => array('isJson' => true),
	),
	// this foreignKey is mainly for crud view generation. model relationship will not use this at the moment
	'json' => array(
		'extra' => array(
		),
		'original' => array(
		),
	),
	'spatial' => array(
		'latlong_address' => array(
			'onChangeLinked' => array('full_address')
		),
	),
	'foreignKey' => array(
		'event_group_code' => array('relationName' => 'event_group', 'model' => 'EventGroup', 'foreignReferAttribute' => 'title'),
		'address_country_code' => array('relationName' => 'country', 'model' => 'Country', 'foreignReferAttribute' => 'printable_name'),
		'address_state_code' => array('relationName' => 'state', 'model' => 'State', 'foreignReferAttribute' => 'title'),
	),
	/*
		eg: resource (this table), industry(target table), resource2industry(linked table)
		key: target table name, all small case singular form, eg 'industry'
		className: the model name of target table, CamelCase with uppercase first character, eg 'Industry'
		relationName: the MANY_MANY relations key generated by yii, all small case plural form of target table name, eg 'industries'
		relationTable: the linked table name, eg 'resource2industry'
		linkClassName: optional, if not provided, CamelCase with uppercase first character of relationTable, eg Resource2Industry
		label: optional
		notMasterData: optional boolean, default: false. If set true, means the target table can be huge so the input method will be different
	*/
	'many2many' => array(
		'industry' => array('className' => 'Industry', 'relationName' => 'industries', 'relationTable' => 'event2industry'),

		'persona' => array('className' => 'Persona', 'relationName' => 'personas', 'relationTable' => 'event2persona'),

		'startup_stage' => array('className' => 'StartupStage', 'relationName' => 'startupStages', 'relationTable' => 'event2startup_stage'),
	),
	'tag' => array(
		'backend' => array(
			'tagTable' => 'tag', 'tagBindingTable' => 'tag2event', 'modelTableFk' => 'event_id', 'tagTablePk' => 'id', 'tagTableName' => 'name', 'tagBindingTableTagId' => 'tag_id', 'cacheID' => 'cacheTag2Event'),
	),
	'neo4j' => array(
		'attributes' => array(
			'id' => 'string',
			'title' => 'string'
		)
	)
);
